version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edifica_db